# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            42
tagline:          that's more than enough
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Oliver Bestwalter
  url:            http:oliver.bestwalter.de
  email:

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/obestwalter/obestwalter.github.io
